### ISSUE TITLE
[Campaign Editor] Error when creating a new project

### ISSUE THREAD

**Issue by Seeker14491** [REHERC/Centrifuge.Mods.Distance#10]
When I try creating a new project I get this error:

![App AdventureMaker Windows_0038](https://user-images.githubusercontent.com/6490497/115947094-0d91cb00-a48b-11eb-8641-6702ef09f7f4.png)

version: `v1.0.171.0`

**Comment by REHERC** [comment]
Seems the error was because i marked all Json fields as "Always Required" and a new project doesn't necessarily have all of them set.
Seems removing the required tag fixed the issue
