### ISSUE TITLE
Custom Car mod problem

### ISSUE THREAD

**Issue by JayBoneJay** [REHERC/Centrifuge.Mods.Distance#6]
I have a problem where anytime I finish a level my level menu is overlayed onto of the main menu which can cause me to leave a server by accident. I would please like this fixed, thanks.

**Comment by JayBoneJay** [comment]
[output_log.txt](https://github.com/REHERC/Centrifuge.Mods.Distance/files/5359656/output_log.txt) output log

**Comment by JayBoneJay** [comment]
[Uploading suzuka-special.txt…]() and car

**Comment by JayBoneJay** [comment]
Better test this time with 
[output_log.txt](https://github.com/REHERC/Centrifuge.Mods.Distance/files/5359672/output_log.txt)
and car is RD-06 found here https://drive.google.com/drive/folders/1U2XFbQUHk6PuEv-_ZX36Da5aEXjYg0eY

**Comment by REHERC** [comment]
Seems like the latest version fixed the issue 😃
